#### 1) Import necessary libs

In [4]:
import pandas as pd
import numpy as np

#### 2) Using the csv file given, create a MultiIndex DataFrame using columns 0, 1, 2 as index and multiColumn using rows 0, 1

In [5]:
df = pd.read_csv(r"C:\Users\sathw\Downloads\multi_index_assignment_261_264-1 - sheet - 1.csv", index_col = [0,1,2], header = [0,1])
df

                                               2014            2015          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Telangana Hyderabad         Smart Phone         253     113      93     223
                            Smart TV            183     213     263     183
                            Air Conditioner     153     233     193     223
          Secunderabad      Smart Phone          93     273     263     213
                            Smart TV            123     123     103     143
                            Air Conditioner     173     163     183     273
          Rangareddy        Smart Phone          93     163     233     263
                            Smart TV            113     213     253     253
                            Air Conditioner     123     103     223     123
Tamilnadu North Chennai     Smart Phone         143     243     173     153
                            Smart TV            273     153     143     283
                            Air Conditioner      93     133      93     153
          South Chennai     Smart Phone         283     143     133     273
                            Smart TV            223     133     173     203
                            Air Conditioner     263     233     193     203
          Central Chennai   Smart Phone         133     263     233     153
                            Smart TV            183     233     163     163
                            Air Conditioner     103     213      93     283
Karnataka North Bangalore   Smart Phone         263     163     153     173
                            Smart TV            103     173     213     203
                            Air Conditioner     113     243     173     113
          South Bangalore   Smart Phone         283      93     113     123
                            Smart TV            143     193     213     243
                            Air Conditioner     203     173     123     213
          Central Bangalore Smart Phone         163     103     283     243
                            Smart TV            263     103     133     103
                            Air Conditioner     143     273     273     103

                                               2016            2017          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Telangana Hyderabad         Smart Phone         173      93      93     253
                            Smart TV            263     113     233     273
                            Air Conditioner     283     143      93     193
          Secunderabad      Smart Phone         173     133     213     113
                            Smart TV            113     143     263     163
                            Air Conditioner     273     133     203     173
          Rangareddy        Smart Phone         243     103     213     253
                            Smart TV            143     273     143     253
                            Air Conditioner     193     253      93     113
Tamilnadu North Chennai     Smart Phone         123     123     183     143
                            Smart TV            273     263     263     133
                            Air Conditioner     163     193     273     243
          South Chennai     Smart Phone         283     263     173     263
                            Smart TV             93     143     103     183
                            Air Conditioner     193     283     173     283
          Central Chennai   Smart Phone         223     193     103     223
                            Smart TV            103     113     213     203
                            Air Conditioner     233     233     233     103
Karnataka North Bangalore   Smart Phone         203     203     143     153
                            Smart TV            253     173     173     113
                            Air Conditioner     253     223     203     113
          South Bangalore   Smart Phone         123     243      93     183
                            Smart TV            223     193     223     203
                            Air Conditioner     153     173     203     213
          Central Bangalore Smart Phone         193     253     183     193
                            Smart TV            223     213     263      93
                            Air Conditioner     103     113     143     243

                                               2018            2019          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Telangana Hyderabad         Smart Phone         153     173     193     203
                            Smart TV            263     273      93     153
                            Air Conditioner     153     153     243     203
          Secunderabad      Smart Phone         133     153     203     123
                            Smart TV             93     243     193     263
                            Air Conditioner     243     163     173     263
          Rangareddy        Smart Phone          93     123     243     123
                            Smart TV            113     173     163      93
                            Air Conditioner     133      93     273     253
Tamilnadu North Chennai     Smart Phone         203     223     103     253
                            Smart TV            113     193     123     263
                            Air Conditioner     263     103     183     173
          South Chennai     Smart Phone         153     283      93     143
                            Smart TV            243     103     113     103
                            Air Conditioner     143     163     263     243
          Central Chennai   Smart Phone         283     153     173     133
                            Smart TV            173     283     213     183
                            Air Conditioner     173     263     283      93
Karnataka North Bangalore   Smart Phone         223     243     103     213
                            Smart TV            143     253     213     103
                            Air Conditioner     213     283     243     143
          South Bangalore   Smart Phone          93     153     113     143
                            Smart TV            123     253     273     273
                            Air Conditioner     213     103     273     123
          Central Bangalore Smart Phone         203     163     253     193
                            Smart TV            273     283     133     123
                            Air Conditioner     283     153     193     153

                                               2020            2021          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Telangana Hyderabad         Smart Phone         193     253     283     193
                            Smart TV            243     253     193     243
                            Air Conditioner     183     113     203     183
          Secunderabad      Smart Phone         263     163     143     183
                            Smart TV            163     153     123     223
                            Air Conditioner     223     233     213     113
          Rangareddy        Smart Phone         283     223     273     213
                            Smart TV            203     183     233     223
                            Air Conditioner     203     253     283     113
Tamilnadu North Chennai     Smart Phone         263     153     153     173
                            Smart TV            173     103     163     233
                            Air Conditioner     213     123     153     123
          South Chennai     Smart Phone         193     163     103     133
                            Smart TV            223     193     213     203
                            Air Conditioner     113     223     223     133
          Central Chennai   Smart Phone         143     153     233     123
                            Smart TV            123     273     173     283
                            Air Conditioner     153     273     113     183
Karnataka North Bangalore   Smart Phone         273     193     213     253
                            Smart TV            173     283     273     233
                            Air Conditioner     203     253     203     253
          South Bangalore   Smart Phone         123     143     263     173
                            Smart TV            203     153     213     203
                            Air Conditioner     163      93     283     143
          Central Bangalore Smart Phone          93      93     123     263
                            Smart TV            163     173      93     153
                            Air Conditioner     193     133     133     123

                                               2022            2023
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Telangana Hyderabad         Smart Phone         103     203     243     153
                            Smart TV             93     263     193     193
                            Air Conditioner     103     273     183     183
          Secunderabad      Smart Phone         203     143     283     133
                            Smart TV            143     253     143     273
                            Air Conditioner     103     113     183     213
          Rangareddy        Smart Phone         213     253     193     173
                            Smart TV            253     183     183     123
                            Air Conditioner     283     173     193     233
Tamilnadu North Chennai     Smart Phone         283     213     243     193
                            Smart TV             93     283     183     133
                            Air Conditioner     203     153     143     223
          South Chennai     Smart Phone         243     103     283     183
                            Smart TV            203     163     143      93
                            Air Conditioner     283     243     243     153
          Central Chennai   Smart Phone         143     233     113     123
                            Smart TV             93     183     213     163
                            Air Conditioner      93     143     193     143
Karnataka North Bangalore   Smart Phone          93     173     213     263
                            Smart TV            213     233     243     163
                            Air Conditioner     273     223     283     183
          South Bangalore   Smart Phone         203     263     143     283
                            Smart TV            133     113     153     193
                            Air Conditioner     143     213     183     103
          Central Bangalore Smart Phone         223     283     113     233
                            Smart TV            243     233     223     203
                            Air Conditioner     253     263     203     153

#### 3) sort the index

In [6]:
df.sort_index()

                                               2014            2015          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Karnataka Central Bangalore Air Conditioner     143     273     273     103
                            Smart Phone         163     103     283     243
                            Smart TV            263     103     133     103
          North Bangalore   Air Conditioner     113     243     173     113
                            Smart Phone         263     163     153     173
                            Smart TV            103     173     213     203
          South Bangalore   Air Conditioner     203     173     123     213
                            Smart Phone         283      93     113     123
                            Smart TV            143     193     213     243
Tamilnadu Central Chennai   Air Conditioner     103     213      93     283
                            Smart Phone         133     263     233     153
                            Smart TV            183     233     163     163
          North Chennai     Air Conditioner      93     133      93     153
                            Smart Phone         143     243     173     153
                            Smart TV            273     153     143     283
          South Chennai     Air Conditioner     263     233     193     203
                            Smart Phone         283     143     133     273
                            Smart TV            223     133     173     203
Telangana Hyderabad         Air Conditioner     153     233     193     223
                            Smart Phone         253     113      93     223
                            Smart TV            183     213     263     183
          Rangareddy        Air Conditioner     123     103     223     123
                            Smart Phone          93     163     233     263
                            Smart TV            113     213     253     253
          Secunderabad      Air Conditioner     173     163     183     273
                            Smart Phone          93     273     263     213
                            Smart TV            123     123     103     143

                                               2016            2017          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Karnataka Central Bangalore Air Conditioner     103     113     143     243
                            Smart Phone         193     253     183     193
                            Smart TV            223     213     263      93
          North Bangalore   Air Conditioner     253     223     203     113
                            Smart Phone         203     203     143     153
                            Smart TV            253     173     173     113
          South Bangalore   Air Conditioner     153     173     203     213
                            Smart Phone         123     243      93     183
                            Smart TV            223     193     223     203
Tamilnadu Central Chennai   Air Conditioner     233     233     233     103
                            Smart Phone         223     193     103     223
                            Smart TV            103     113     213     203
          North Chennai     Air Conditioner     163     193     273     243
                            Smart Phone         123     123     183     143
                            Smart TV            273     263     263     133
          South Chennai     Air Conditioner     193     283     173     283
                            Smart Phone         283     263     173     263
                            Smart TV             93     143     103     183
Telangana Hyderabad         Air Conditioner     283     143      93     193
                            Smart Phone         173      93      93     253
                            Smart TV            263     113     233     273
          Rangareddy        Air Conditioner     193     253      93     113
                            Smart Phone         243     103     213     253
                            Smart TV            143     273     143     253
          Secunderabad      Air Conditioner     273     133     203     173
                            Smart Phone         173     133     213     113
                            Smart TV            113     143     263     163

                                               2018            2019          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Karnataka Central Bangalore Air Conditioner     283     153     193     153
                            Smart Phone         203     163     253     193
                            Smart TV            273     283     133     123
          North Bangalore   Air Conditioner     213     283     243     143
                            Smart Phone         223     243     103     213
                            Smart TV            143     253     213     103
          South Bangalore   Air Conditioner     213     103     273     123
                            Smart Phone          93     153     113     143
                            Smart TV            123     253     273     273
Tamilnadu Central Chennai   Air Conditioner     173     263     283      93
                            Smart Phone         283     153     173     133
                            Smart TV            173     283     213     183
          North Chennai     Air Conditioner     263     103     183     173
                            Smart Phone         203     223     103     253
                            Smart TV            113     193     123     263
          South Chennai     Air Conditioner     143     163     263     243
                            Smart Phone         153     283      93     143
                            Smart TV            243     103     113     103
Telangana Hyderabad         Air Conditioner     153     153     243     203
                            Smart Phone         153     173     193     203
                            Smart TV            263     273      93     153
          Rangareddy        Air Conditioner     133      93     273     253
                            Smart Phone          93     123     243     123
                            Smart TV            113     173     163      93
          Secunderabad      Air Conditioner     243     163     173     263
                            Smart Phone         133     153     203     123
                            Smart TV             93     243     193     263

                                               2020            2021          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Karnataka Central Bangalore Air Conditioner     193     133     133     123
                            Smart Phone          93      93     123     263
                            Smart TV            163     173      93     153
          North Bangalore   Air Conditioner     203     253     203     253
                            Smart Phone         273     193     213     253
                            Smart TV            173     283     273     233
          South Bangalore   Air Conditioner     163      93     283     143
                            Smart Phone         123     143     263     173
                            Smart TV            203     153     213     203
Tamilnadu Central Chennai   Air Conditioner     153     273     113     183
                            Smart Phone         143     153     233     123
                            Smart TV            123     273     173     283
          North Chennai     Air Conditioner     213     123     153     123
                            Smart Phone         263     153     153     173
                            Smart TV            173     103     163     233
          South Chennai     Air Conditioner     113     223     223     133
                            Smart Phone         193     163     103     133
                            Smart TV            223     193     213     203
Telangana Hyderabad         Air Conditioner     183     113     203     183
                            Smart Phone         193     253     283     193
                            Smart TV            243     253     193     243
          Rangareddy        Air Conditioner     203     253     283     113
                            Smart Phone         283     223     273     213
                            Smart TV            203     183     233     223
          Secunderabad      Air Conditioner     223     233     213     113
                            Smart Phone         263     163     143     183
                            Smart TV            163     153     123     223

                                               2022            2023
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Karnataka Central Bangalore Air Conditioner     253     263     203     153
                            Smart Phone         223     283     113     233
                            Smart TV            243     233     223     203
          North Bangalore   Air Conditioner     273     223     283     183
                            Smart Phone          93     173     213     263
                            Smart TV            213     233     243     163
          South Bangalore   Air Conditioner     143     213     183     103
                            Smart Phone         203     263     143     283
                            Smart TV            133     113     153     193
Tamilnadu Central Chennai   Air Conditioner      93     143     193     143
                            Smart Phone         143     233     113     123
                            Smart TV             93     183     213     163
          North Chennai     Air Conditioner     203     153     143     223
                            Smart Phone         283     213     243     193
                            Smart TV             93     283     183     133
          South Chennai     Air Conditioner     283     243     243     153
                            Smart Phone         243     103     283     183
                            Smart TV            203     163     143      93
Telangana Hyderabad         Air Conditioner     103     273     183     183
                            Smart Phone         103     203     243     153
                            Smart TV             93     263     193     193
          Rangareddy        Air Conditioner     283     173     193     233
                            Smart Phone         213     253     193     173
                            Smart TV            253     183     183     123
          Secunderabad      Air Conditioner     103     113     183     213
                            Smart Phone         203     143     283     133
                            Smart TV            143     253     143     273

#### 4) Name the index cols as State, Region, Product and the multicol levels as Year and Semester

In [7]:
xx = df.rename_axis(index = ['State' , 'Region', 'Product' ])
xx

                                               2014            2015          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         253     113      93     223
                            Smart TV            183     213     263     183
                            Air Conditioner     153     233     193     223
          Secunderabad      Smart Phone          93     273     263     213
                            Smart TV            123     123     103     143
                            Air Conditioner     173     163     183     273
          Rangareddy        Smart Phone          93     163     233     263
                            Smart TV            113     213     253     253
                            Air Conditioner     123     103     223     123
Tamilnadu North Chennai     Smart Phone         143     243     173     153
                            Smart TV            273     153     143     283
                            Air Conditioner      93     133      93     153
          South Chennai     Smart Phone         283     143     133     273
                            Smart TV            223     133     173     203
                            Air Conditioner     263     233     193     203
          Central Chennai   Smart Phone         133     263     233     153
                            Smart TV            183     233     163     163
                            Air Conditioner     103     213      93     283
Karnataka North Bangalore   Smart Phone         263     163     153     173
                            Smart TV            103     173     213     203
                            Air Conditioner     113     243     173     113
          South Bangalore   Smart Phone         283      93     113     123
                            Smart TV            143     193     213     243
                            Air Conditioner     203     173     123     213
          Central Bangalore Smart Phone         163     103     283     243
                            Smart TV            263     103     133     103
                            Air Conditioner     143     273     273     103

                                               2016            2017          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         173      93      93     253
                            Smart TV            263     113     233     273
                            Air Conditioner     283     143      93     193
          Secunderabad      Smart Phone         173     133     213     113
                            Smart TV            113     143     263     163
                            Air Conditioner     273     133     203     173
          Rangareddy        Smart Phone         243     103     213     253
                            Smart TV            143     273     143     253
                            Air Conditioner     193     253      93     113
Tamilnadu North Chennai     Smart Phone         123     123     183     143
                            Smart TV            273     263     263     133
                            Air Conditioner     163     193     273     243
          South Chennai     Smart Phone         283     263     173     263
                            Smart TV             93     143     103     183
                            Air Conditioner     193     283     173     283
          Central Chennai   Smart Phone         223     193     103     223
                            Smart TV            103     113     213     203
                            Air Conditioner     233     233     233     103
Karnataka North Bangalore   Smart Phone         203     203     143     153
                            Smart TV            253     173     173     113
                            Air Conditioner     253     223     203     113
          South Bangalore   Smart Phone         123     243      93     183
                            Smart TV            223     193     223     203
                            Air Conditioner     153     173     203     213
          Central Bangalore Smart Phone         193     253     183     193
                            Smart TV            223     213     263      93
                            Air Conditioner     103     113     143     243

                                               2018            2019          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         153     173     193     203
                            Smart TV            263     273      93     153
                            Air Conditioner     153     153     243     203
          Secunderabad      Smart Phone         133     153     203     123
                            Smart TV             93     243     193     263
                            Air Conditioner     243     163     173     263
          Rangareddy        Smart Phone          93     123     243     123
                            Smart TV            113     173     163      93
                            Air Conditioner     133      93     273     253
Tamilnadu North Chennai     Smart Phone         203     223     103     253
                            Smart TV            113     193     123     263
                            Air Conditioner     263     103     183     173
          South Chennai     Smart Phone         153     283      93     143
                            Smart TV            243     103     113     103
                            Air Conditioner     143     163     263     243
          Central Chennai   Smart Phone         283     153     173     133
                            Smart TV            173     283     213     183
                            Air Conditioner     173     263     283      93
Karnataka North Bangalore   Smart Phone         223     243     103     213
                            Smart TV            143     253     213     103
                            Air Conditioner     213     283     243     143
          South Bangalore   Smart Phone          93     153     113     143
                            Smart TV            123     253     273     273
                            Air Conditioner     213     103     273     123
          Central Bangalore Smart Phone         203     163     253     193
                            Smart TV            273     283     133     123
                            Air Conditioner     283     153     193     153

                                               2020            2021          \
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         193     253     283     193
                            Smart TV            243     253     193     243
                            Air Conditioner     183     113     203     183
          Secunderabad      Smart Phone         263     163     143     183
                            Smart TV            163     153     123     223
                            Air Conditioner     223     233     213     113
          Rangareddy        Smart Phone         283     223     273     213
                            Smart TV            203     183     233     223
                            Air Conditioner     203     253     283     113
Tamilnadu North Chennai     Smart Phone         263     153     153     173
                            Smart TV            173     103     163     233
                            Air Conditioner     213     123     153     123
          South Chennai     Smart Phone         193     163     103     133
                            Smart TV            223     193     213     203
                            Air Conditioner     113     223     223     133
          Central Chennai   Smart Phone         143     153     233     123
                            Smart TV            123     273     173     283
                            Air Conditioner     153     273     113     183
Karnataka North Bangalore   Smart Phone         273     193     213     253
                            Smart TV            173     283     273     233
                            Air Conditioner     203     253     203     253
          South Bangalore   Smart Phone         123     143     263     173
                            Smart TV            203     153     213     203
                            Air Conditioner     163      93     283     143
          Central Bangalore Smart Phone          93      93     123     263
                            Smart TV            163     173      93     153
                            Air Conditioner     193     133     133     123

                                               2022            2023
                                            Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         103     203     243     153
                            Smart TV             93     263     193     193
                            Air Conditioner     103     273     183     183
          Secunderabad      Smart Phone         203     143     283     133
                            Smart TV            143     253     143     273
                            Air Conditioner     103     113     183     213
          Rangareddy        Smart Phone         213     253     193     173
                            Smart TV            253     183     183     123
                            Air Conditioner     283     173     193     233
Tamilnadu North Chennai     Smart Phone         283     213     243     193
                            Smart TV             93     283     183     133
                            Air Conditioner     203     153     143     223
          South Chennai     Smart Phone         243     103     283     183
                            Smart TV            203     163     143      93
                            Air Conditioner     283     243     243     153
          Central Chennai   Smart Phone         143     233     113     123
                            Smart TV             93     183     213     163
                            Air Conditioner      93     143     193     143
Karnataka North Bangalore   Smart Phone          93     173     213     263
                            Smart TV            213     233     243     163
                            Air Conditioner     273     223     283     183
          South Bangalore   Smart Phone         203     263     143     283
                            Smart TV            133     113     153     193
                            Air Conditioner     143     213     183     103
          Central Bangalore Smart Phone         223     283     113     233
                            Smart TV            243     233     223     203
                            Air Conditioner     253     263     203     153

In [8]:
y = xx.rename_axis(columns = ['year', 'semester'])
y

year                                           2014            2015          \
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         253     113      93     223
                            Smart TV            183     213     263     183
                            Air Conditioner     153     233     193     223
          Secunderabad      Smart Phone          93     273     263     213
                            Smart TV            123     123     103     143
                            Air Conditioner     173     163     183     273
          Rangareddy        Smart Phone          93     163     233     263
                            Smart TV            113     213     253     253
                            Air Conditioner     123     103     223     123
Tamilnadu North Chennai     Smart Phone         143     243     173     153
                            Smart TV            273     153     143     283
                            Air Conditioner      93     133      93     153
          South Chennai     Smart Phone         283     143     133     273
                            Smart TV            223     133     173     203
                            Air Conditioner     263     233     193     203
          Central Chennai   Smart Phone         133     263     233     153
                            Smart TV            183     233     163     163
                            Air Conditioner     103     213      93     283
Karnataka North Bangalore   Smart Phone         263     163     153     173
                            Smart TV            103     173     213     203
                            Air Conditioner     113     243     173     113
          South Bangalore   Smart Phone         283      93     113     123
                            Smart TV            143     193     213     243
                            Air Conditioner     203     173     123     213
          Central Bangalore Smart Phone         163     103     283     243
                            Smart TV            263     103     133     103
                            Air Conditioner     143     273     273     103

year                                           2016            2017          \
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         173      93      93     253
                            Smart TV            263     113     233     273
                            Air Conditioner     283     143      93     193
          Secunderabad      Smart Phone         173     133     213     113
                            Smart TV            113     143     263     163
                            Air Conditioner     273     133     203     173
          Rangareddy        Smart Phone         243     103     213     253
                            Smart TV            143     273     143     253
                            Air Conditioner     193     253      93     113
Tamilnadu North Chennai     Smart Phone         123     123     183     143
                            Smart TV            273     263     263     133
                            Air Conditioner     163     193     273     243
          South Chennai     Smart Phone         283     263     173     263
                            Smart TV             93     143     103     183
                            Air Conditioner     193     283     173     283
          Central Chennai   Smart Phone         223     193     103     223
                            Smart TV            103     113     213     203
                            Air Conditioner     233     233     233     103
Karnataka North Bangalore   Smart Phone         203     203     143     153
                            Smart TV            253     173     173     113
                            Air Conditioner     253     223     203     113
          South Bangalore   Smart Phone         123     243      93     183
                            Smart TV            223     193     223     203
                            Air Conditioner     153     173     203     213
          Central Bangalore Smart Phone         193     253     183     193
                            Smart TV            223     213     263      93
                            Air Conditioner     103     113     143     243

year                                           2018            2019          \
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         153     173     193     203
                            Smart TV            263     273      93     153
                            Air Conditioner     153     153     243     203
          Secunderabad      Smart Phone         133     153     203     123
                            Smart TV             93     243     193     263
                            Air Conditioner     243     163     173     263
          Rangareddy        Smart Phone          93     123     243     123
                            Smart TV            113     173     163      93
                            Air Conditioner     133      93     273     253
Tamilnadu North Chennai     Smart Phone         203     223     103     253
                            Smart TV            113     193     123     263
                            Air Conditioner     263     103     183     173
          South Chennai     Smart Phone         153     283      93     143
                            Smart TV            243     103     113     103
                            Air Conditioner     143     163     263     243
          Central Chennai   Smart Phone         283     153     173     133
                            Smart TV            173     283     213     183
                            Air Conditioner     173     263     283      93
Karnataka North Bangalore   Smart Phone         223     243     103     213
                            Smart TV            143     253     213     103
                            Air Conditioner     213     283     243     143
          South Bangalore   Smart Phone          93     153     113     143
                            Smart TV            123     253     273     273
                            Air Conditioner     213     103     273     123
          Central Bangalore Smart Phone         203     163     253     193
                            Smart TV            273     283     133     123
                            Air Conditioner     283     153     193     153

year                                           2020            2021          \
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         193     253     283     193
                            Smart TV            243     253     193     243
                            Air Conditioner     183     113     203     183
          Secunderabad      Smart Phone         263     163     143     183
                            Smart TV            163     153     123     223
                            Air Conditioner     223     233     213     113
          Rangareddy        Smart Phone         283     223     273     213
                            Smart TV            203     183     233     223
                            Air Conditioner     203     253     283     113
Tamilnadu North Chennai     Smart Phone         263     153     153     173
                            Smart TV            173     103     163     233
                            Air Conditioner     213     123     153     123
          South Chennai     Smart Phone         193     163     103     133
                            Smart TV            223     193     213     203
                            Air Conditioner     113     223     223     133
          Central Chennai   Smart Phone         143     153     233     123
                            Smart TV            123     273     173     283
                            Air Conditioner     153     273     113     183
Karnataka North Bangalore   Smart Phone         273     193     213     253
                            Smart TV            173     283     273     233
                            Air Conditioner     203     253     203     253
          South Bangalore   Smart Phone         123     143     263     173
                            Smart TV            203     153     213     203
                            Air Conditioner     163      93     283     143
          Central Bangalore Smart Phone          93      93     123     263
                            Smart TV            163     173      93     153
                            Air Conditioner     193     133     133     123

year                                           2022            2023
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart Phone         103     203     243     153
                            Smart TV             93     263     193     193
                            Air Conditioner     103     273     183     183
          Secunderabad      Smart Phone         203     143     283     133
                            Smart TV            143     253     143     273
                            Air Conditioner     103     113     183     213
          Rangareddy        Smart Phone         213     253     193     173
                            Smart TV            253     183     183     123
                            Air Conditioner     283     173     193     233
Tamilnadu North Chennai     Smart Phone         283     213     243     193
                            Smart TV             93     283     183     133
                            Air Conditioner     203     153     143     223
          South Chennai     Smart Phone         243     103     283     183
                            Smart TV            203     163     143      93
                            Air Conditioner     283     243     243     153
          Central Chennai   Smart Phone         143     233     113     123
                            Smart TV             93     183     213     163
                            Air Conditioner      93     143     193     143
Karnataka North Bangalore   Smart Phone          93     173     213     263
                            Smart TV            213     233     243     163
                            Air Conditioner     273     223     283     183
          South Bangalore   Smart Phone         203     263     143     283
                            Smart TV            133     113     153     193
                            Air Conditioner     143     213     183     103
          Central Bangalore Smart Phone         223     283     113     233
                            Smart TV            243     233     223     203
                            Air Conditioner     253     263     203     153

#### 5) Using .loc method, find the number of units of Smart Tv sold in Central Channai in year 2020

In [9]:
xx = y.loc[('Tamilnadu' , 'Central Chennai', 'Smart TV'),('2020', 'Jan-Jun')]
xx

123

In [10]:
x = y.loc[('Tamilnadu', 'Central Chennai', 'Smart TV'),('2020', 'Jul-Dec')]
x

273

In [11]:
smart_tv_sold_2020 = xx + x
smart_tv_sold_2020

396

#### 6) using .loc and slice(), get the records from Rangareddy, Telangana and all records from Tamilnadu for years 'Jul-Dec' of 2016 till & including 2019

In [12]:
y.loc[('Tamilnadu'),(slice('2016','2019'), 'Jul-Dec')]

year                               2016    2017    2018    2019
semester                        Jul-Dec Jul-Dec Jul-Dec Jul-Dec
Region          Product
North Chennai   Smart Phone         123     143     223     253
                Smart TV            263     133     193     263
                Air Conditioner     193     243     103     173
South Chennai   Smart Phone         263     263     283     143
                Smart TV            143     183     103     103
                Air Conditioner     283     283     163     243
Central Chennai Smart Phone         193     223     153     133
                Smart TV            113     203     283     183
                Air Conditioner     233     103     263      93

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
y.loc[('Telangana', 'Rangareddy'), (slice('2016','2019'), 'Jul-Dec')]

year               2016    2017    2018    2019
semester        Jul-Dec Jul-Dec Jul-Dec Jul-Dec
Product
Smart Phone         103     253     123     123
Smart TV            273     253     173      93
Air Conditioner     253     113      93     253

#### 7) using .xs(), get all the records from Karnataka belonging to Air Conditioner

In [15]:
y.xs(('Karnataka',slice(None),'Air Conditioner'),level=(0,1,2),drop_level=False,)

year                                           2014            2015          \
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Karnataka North Bangalore   Air Conditioner     113     243     173     113
          South Bangalore   Air Conditioner     203     173     123     213
          Central Bangalore Air Conditioner     143     273     273     103

year                                           2016            2017          \
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Karnataka North Bangalore   Air Conditioner     253     223     203     113
          South Bangalore   Air Conditioner     153     173     203     213
          Central Bangalore Air Conditioner     103     113     143     243

year                                           2018            2019          \
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Karnataka North Bangalore   Air Conditioner     213     283     243     143
          South Bangalore   Air Conditioner     213     103     273     123
          Central Bangalore Air Conditioner     283     153     193     153

year                                           2020            2021          \
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Karnataka North Bangalore   Air Conditioner     203     253     203     253
          South Bangalore   Air Conditioner     163      93     283     143
          Central Bangalore Air Conditioner     193     133     133     123

year                                           2022            2023
semester                                    Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Karnataka North Bangalore   Air Conditioner     273     223     283     183
          South Bangalore   Air Conditioner     143     213     183     103
          Central Bangalore Air Conditioner     253     263     203     153

#### 8) using .xs(), get all the records from 'Jan-Jun'

In [18]:
# cross section
y.xs('Jan-Jun',level= 'semester',axis=1)

year                                         2014  2015  2016  2017  2018  \
State     Region            Product
Telangana Hyderabad         Smart Phone       253    93   173    93   153
                            Smart TV          183   263   263   233   263
                            Air Conditioner   153   193   283    93   153
          Secunderabad      Smart Phone        93   263   173   213   133
                            Smart TV          123   103   113   263    93
                            Air Conditioner   173   183   273   203   243
          Rangareddy        Smart Phone        93   233   243   213    93
                            Smart TV          113   253   143   143   113
                            Air Conditioner   123   223   193    93   133
Tamilnadu North Chennai     Smart Phone       143   173   123   183   203
                            Smart TV          273   143   273   263   113
                            Air Conditioner    93    93   163   273   263
          South Chennai     Smart Phone       283   133   283   173   153
                            Smart TV          223   173    93   103   243
                            Air Conditioner   263   193   193   173   143
          Central Chennai   Smart Phone       133   233   223   103   283
                            Smart TV          183   163   103   213   173
                            Air Conditioner   103    93   233   233   173
Karnataka North Bangalore   Smart Phone       263   153   203   143   223
                            Smart TV          103   213   253   173   143
                            Air Conditioner   113   173   253   203   213
          South Bangalore   Smart Phone       283   113   123    93    93
                            Smart TV          143   213   223   223   123
                            Air Conditioner   203   123   153   203   213
          Central Bangalore Smart Phone       163   283   193   183   203
                            Smart TV          263   133   223   263   273
                            Air Conditioner   143   273   103   143   283

year                                         2019  2020  2021  2022  2023
State     Region            Product
Telangana Hyderabad         Smart Phone       193   193   283   103   243
                            Smart TV           93   243   193    93   193
                            Air Conditioner   243   183   203   103   183
          Secunderabad      Smart Phone       203   263   143   203   283
                            Smart TV          193   163   123   143   143
                            Air Conditioner   173   223   213   103   183
          Rangareddy        Smart Phone       243   283   273   213   193
                            Smart TV          163   203   233   253   183
                            Air Conditioner   273   203   283   283   193
Tamilnadu North Chennai     Smart Phone       103   263   153   283   243
                            Smart TV          123   173   163    93   183
                            Air Conditioner   183   213   153   203   143
          South Chennai     Smart Phone        93   193   103   243   283
                            Smart TV          113   223   213   203   143
                            Air Conditioner   263   113   223   283   243
          Central Chennai   Smart Phone       173   143   233   143   113
                            Smart TV          213   123   173    93   213
                            Air Conditioner   283   153   113    93   193
Karnataka North Bangalore   Smart Phone       103   273   213    93   213
                            Smart TV          213   173   273   213   243
                            Air Conditioner   243   203   203   273   283
          South Bangalore   Smart Phone       113   123   263   203   143
                            Smart TV          273   203   213   133   153
                            Air Conditioner   273   163   283   143   183
          Central Bangalore Smart Phone       253    93   123   223   113
                            Smart TV          133   163    93   243   223
                            Air Conditioner   193   193   133   253   203

#### 9) using 'get_level_values', get all records belonging to 'Smart TV'

In [35]:
y[y.index.get_level_values('Product') == 'Smart TV']

year                                    2014            2015            2016  \
semester                             Jan-Jun Jul-Dec Jan-Jun Jul-Dec Jan-Jun
State     Region            Product
Telangana Hyderabad         Smart TV     183     213     263     183     263
          Secunderabad      Smart TV     123     123     103     143     113
          Rangareddy        Smart TV     113     213     253     253     143
Tamilnadu North Chennai     Smart TV     273     153     143     283     273
          South Chennai     Smart TV     223     133     173     203      93
          Central Chennai   Smart TV     183     233     163     163     103
Karnataka North Bangalore   Smart TV     103     173     213     203     253
          South Bangalore   Smart TV     143     193     213     243     223
          Central Bangalore Smart TV     263     103     133     103     223

year                                            2017            2018          \
semester                             Jul-Dec Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart TV     113     233     273     263     273
          Secunderabad      Smart TV     143     263     163      93     243
          Rangareddy        Smart TV     273     143     253     113     173
Tamilnadu North Chennai     Smart TV     263     263     133     113     193
          South Chennai     Smart TV     143     103     183     243     103
          Central Chennai   Smart TV     113     213     203     173     283
Karnataka North Bangalore   Smart TV     173     173     113     143     253
          South Bangalore   Smart TV     193     223     203     123     253
          Central Bangalore Smart TV     213     263      93     273     283

year                                    2019            2020            2021  \
semester                             Jan-Jun Jul-Dec Jan-Jun Jul-Dec Jan-Jun
State     Region            Product
Telangana Hyderabad         Smart TV      93     153     243     253     193
          Secunderabad      Smart TV     193     263     163     153     123
          Rangareddy        Smart TV     163      93     203     183     233
Tamilnadu North Chennai     Smart TV     123     263     173     103     163
          South Chennai     Smart TV     113     103     223     193     213
          Central Chennai   Smart TV     213     183     123     273     173
Karnataka North Bangalore   Smart TV     213     103     173     283     273
          South Bangalore   Smart TV     273     273     203     153     213
          Central Bangalore Smart TV     133     123     163     173      93

year                                            2022            2023
semester                             Jul-Dec Jan-Jun Jul-Dec Jan-Jun Jul-Dec
State     Region            Product
Telangana Hyderabad         Smart TV     243      93     263     193     193
          Secunderabad      Smart TV     223     143     253     143     273
          Rangareddy        Smart TV     223     253     183     183     123
Tamilnadu North Chennai     Smart TV     233      93     283     183     133
          South Chennai     Smart TV     203     203     163     143      93
          Central Chennai   Smart TV     283      93     183     213     163
Karnataka North Bangalore   Smart TV     233     213     233     243     163
          South Bangalore   Smart TV     203     133     113     153     193
          Central Bangalore Smart TV     153     243     233     223     203

#### 10) Give a detailed data about the Tamilnadu, and then tell me how many items were sold in total from this warehouse over the 10 year period?

In [54]:
y.loc['Tamilnadu']

year                               2014            2015            2016  \
semester                        Jan-Jun Jul-Dec Jan-Jun Jul-Dec Jan-Jun
Region          Product
North Chennai   Smart Phone         143     243     173     153     123
                Smart TV            273     153     143     283     273
                Air Conditioner      93     133      93     153     163
South Chennai   Smart Phone         283     143     133     273     283
                Smart TV            223     133     173     203      93
                Air Conditioner     263     233     193     203     193
Central Chennai Smart Phone         133     263     233     153     223
                Smart TV            183     233     163     163     103
                Air Conditioner     103     213      93     283     233

year                                       2017            2018          \
semester                        Jul-Dec Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Region          Product
North Chennai   Smart Phone         123     183     143     203     223
                Smart TV            263     263     133     113     193
                Air Conditioner     193     273     243     263     103
South Chennai   Smart Phone         263     173     263     153     283
                Smart TV            143     103     183     243     103
                Air Conditioner     283     173     283     143     163
Central Chennai Smart Phone         193     103     223     283     153
                Smart TV            113     213     203     173     283
                Air Conditioner     233     233     103     173     263

year                               2019            2020            2021  \
semester                        Jan-Jun Jul-Dec Jan-Jun Jul-Dec Jan-Jun
Region          Product
North Chennai   Smart Phone         103     253     263     153     153
                Smart TV            123     263     173     103     163
                Air Conditioner     183     173     213     123     153
South Chennai   Smart Phone          93     143     193     163     103
                Smart TV            113     103     223     193     213
                Air Conditioner     263     243     113     223     223
Central Chennai Smart Phone         173     133     143     153     233
                Smart TV            213     183     123     273     173
                Air Conditioner     283      93     153     273     113

year                                       2022            2023
semester                        Jul-Dec Jan-Jun Jul-Dec Jan-Jun Jul-Dec
Region          Product
North Chennai   Smart Phone         173     283     213     243     193
                Smart TV            233      93     283     183     133
                Air Conditioner     123     203     153     143     223
South Chennai   Smart Phone         133     243     103     283     183
                Smart TV            203     203     163     143      93
                Air Conditioner     133     283     243     243     153
Central Chennai Smart Phone         123     143     233     113     123
                Smart TV            283      93     183     213     163
                Air Conditioner     183      93     143     193     143

In [60]:
y.loc['Tamilnadu'].sum().sum()

33230

#### 11) How many Smart TV were sold in Telangana & Karnataka during the year 2017?

In [119]:
telangana = y.loc[('Telangana', slice(None), 'Smart TV'), ('2017', slice(None))]
karnataka = y.loc[('Karnataka', slice(None), 'Smart TV'), ('2017', slice(None))]
two_states = telangana.sum() + karnataka.sum()

print(telangana, '\n\n')
print(karnataka, '\n\n')

print(f'total no.of Smart TV\'s sold are : ', two_states.sum())

year                               2017
semester                        Jan-Jun Jul-Dec
State     Region       Product
Telangana Hyderabad    Smart TV     233     273
          Secunderabad Smart TV     263     163
          Rangareddy   Smart TV     143     253


year                                    2017
semester                             Jan-Jun Jul-Dec
State     Region            Product
Karnataka North Bangalore   Smart TV     173     113
          South Bangalore   Smart TV     223     203
          Central Bangalore Smart TV     263      93


total no.of Smart TV's sold are :  2396

#### 12) Get me list of all items that were sold in the Jul-Dec semester of the year 2020 for all States

In [126]:
y.loc[:, ('2020','Jul-Dec')]

State      Region             Product
Telangana  Hyderabad          Smart Phone        253
                              Smart TV           253
                              Air Conditioner    113
           Secunderabad       Smart Phone        163
                              Smart TV           153
                              Air Conditioner    233
           Rangareddy         Smart Phone        223
                              Smart TV           183
                              Air Conditioner    253
Tamilnadu  North Chennai      Smart Phone        153
                              Smart TV           103
                              Air Conditioner    123
           South Chennai      Smart Phone        163
                              Smart TV           193
                              Air Conditioner    223
           Central Chennai    Smart Phone        153
                              Smart TV           273
                              Air Conditioner    273
Karnataka  North Bangalore    Smart Phone        193
                              Smart TV           283
                              Air Conditioner    253
           South Bangalore    Smart Phone        143
                              Smart TV           153
                              Air Conditioner     93
           Central Bangalore  Smart Phone         93
                              Smart TV           173
                              Air Conditioner    133
Name: (2020, Jul-Dec), dtype: int64

#### 13) What method is used to know if the MultiIndex index is sorted or not

In [127]:
#the following method is used to know the multiindex is sorted or not
xx = y.index._is_lexsorted()
xx

False